USE score;
INSERT INTO admin(account, password, username, is_super) VALUES ("chenliwei", "chenliwei123", "陈李维", 1);
INSERT INTO user(account, username, password, education, grade) VALUES ("ylhao", "衣龙浩", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("xiaohua", "肖华", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("shecairui", "佘才睿", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("gaoyuhan", "高语晗", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("yangyaxuan", "杨雅轩", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("zhangfei", "张飞", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("xuqizhen", "许奇臻", "123456", "硕士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("luguorui", "卢国瑞", "123456", "硕士", "三年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("guoyingjie", "郭英杰", "123456", "硕士", "三年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("zhangyuantong", "张元瞳", "123456", "硕士", "三年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("tianlinan", "田力楠", "123456", "硕士", "三年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("lijinfeng", "李锦峰", "123456", "博士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("mamengyu", "马梦雨", "123456", "博士", "二年级");
INSERT INTO user(account, username, password, education, grade) VALUES ("liutong", "柳童", "123456", "博士", "三年级");
